apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: finnfastlege
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  envFrom:
    - secret: finnfastlege-session-key
  env:
    - name: NODE_ENV
      value: production
    - name: REDIS_HOST
      value: finnfastlege-redis
    - name: FINNFASTLEGE_URL
      value: "http://finnfastlege"
    - name: AUTH_REDIRECT_URI
      value: "https://finnfastlege.intern.dev.nav.no/oauth2/callback"
    - name: INTERNARBEIDSFLATEDECORATOR_HOST
      value: "internarbeidsflatedecorator-q1.dev-fss-pub.nais.io"
    - name: FASTLEGEREST_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.fastlegerest"
    - name: SYFOPERSON_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfoperson"
    - name: MODIACONTEXTHOLDER_AAD_APP_CLIENT_ID
      value: "dev-fss.personoversikt.modiacontextholder-q1"
    - name: SYFOTILGANGSKONTROLL_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfo-tilgangskontroll"
    - name: MODIACONTEXTHOLDER_HOST
      value: "https://modiacontextholder-q1.dev-fss-pub.nais.io"
    - name: FASTLEGEREST_HOST
      value: "http://fastlegerest"
    - name: SYFOPERSON_HOST
      value: "http://syfoperson"
    - name: SYFOTILGANGKONTROLL_HOST
      value: "http://syfo-tilgangskontroll"
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  accessPolicy:
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "internarbeidsflatedecorator-q1.dev-fss-pub.nais.io"
        - host: "modiacontextholder-q1.dev-fss-pub.nais.io"
      rules:
        - application: fastlegerest
        - application: syfo-tilgangskontroll
        - application: syfoperson
        - application: finnfastlege-redis
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  ingresses:
    - "https://finnfastlege.intern.dev.nav.no"
