export const HENT_FASTLEGE_FORESPURT = 'HENT_FASTLEGE_FORESPURT';
export const HENTER_FASTLEGE = 'HENTER_FASTLEGE';
export const HENT_FASTLEGE_FEILET = 'HENT_FASTLEGE_FEILET';
export const FASTLEGE_HENTET = 'FASTLEGE_HENTET';
export const FASTLEGE_IKKE_FUNNET = 'FASTLEGE_IKKE_FUNNET';
export const FASTLEGE_IKKE_TILGANG = 'FASTLEGE_IKKE_TILGANG';

export const SJEKK_FASTLEGE_TILGANG_FORESPURT = 'SJEKK_FASTLEGE_TILGANG_FORESPURT';
export const SJEKKER_FASTLEGE_TILGANG = 'SJEKKER_FASTLEGE_TILGANG';
export const SJEKK_FASTLEGE_TILGANG_FEILET = 'SJEKK_FASTLEGE_TILGANG_FEILET';
export const FASTLEGE_TILGANG_HENTET = 'FASTLEGE_TILGANG_HENTET';

export const PUSH_MODIACONTEXT_FORESPURT = 'PUSH_MODIACONTEXT_FORESPURT';
export const PUSH_MODIACONTEXT_FEILET = 'PUSH_MODIACONTEXT_FEILET';
export const MODIACONTEXT_PUSHET = 'MODIACONTEXT_PUSHET';
export const PUSHER_MODIACONTEXT = 'PUSHER_MODIACONTEXT';

export const HENT_AKTIVENHET_FORESPURT = 'HENT_AKTIVENHET_FORESPURT';
export const HENTER_AKTIVENHET = 'HENTER_AKTIVENHET';
export const HENT_AKTIVENHET_FEILET = 'HENT_AKTIVENHET_FEILET';
export const AKTIVENHET_HENTET = 'AKTIVENHET_HENTET';

export const HENT_EGENANSATT_FORESPURT = 'HENT_EGENANSATT_FORESPURT';
export const HENTER_EGENANSATT = 'HENTER_EGENANSATT';
export const HENT_EGENANSATT_FEILET = 'HENT_EGENANSATT_FEILET';
export const EGENANSATT_HENTET = 'EGENANSATT_HENTET';

export const HENT_DISKRESJONSKODE_FORESPURT = 'HENT_DISKRESJONSKODE_FORESPURT';
export const HENTER_DISKRESJONSKODE = 'HENTER_DISKRESJONSKODE';
export const HENT_DISKRESJONSKODE_FEILET = 'HENT_DISKRESJONSKODE_FEILET';
export const DISKRESJONSKODE_HENTET = 'DISKRESJONSKODE_HENTET';

export const HENT_VEILEDERINFO_FORESPURT = 'HENT_VEILEDERINFO_FORESPURT';
export const HENTER_VEILEDERINFO = 'HENTER_VEILEDERINFO';
export const HENT_VEILEDERINFO_FEILET = 'HENT_VEILEDERINFO_FEILET';
export const VEILEDERINFO_HENTET = 'VEILEDERINFO_HENTET';
