export const HENT_FASTLEGE_FORESPURT = 'HENT_FASTLEGE_FORESPURT';
export const HENTER_FASTLEGE = 'HENTER_FASTLEGE';
export const HENT_FASTLEGE_FEILET = 'HENT_FASTLEGE_FEILET';
export const FASTLEGE_HENTET = 'FASTLEGE_HENTET';
export const FASTLEGE_IKKE_FUNNET = 'FASTLEGE_IKKE_FUNNET';
export const FASTLEGE_IKKE_TILGANG = 'FASTLEGE_IKKE_TILGANG';

export const SJEKK_FASTLEGE_TILGANG_FORESPURT = 'SJEKK_FASTLEGE_TILGANG_FORESPURT';
export const SJEKKER_FASTLEGE_TILGANG = 'SJEKKER_FASTLEGE_TILGANG';
export const SJEKK_FASTLEGE_TILGANG_FEILET = 'SJEKK_FASTLEGE_TILGANG_FEILET';
export const FASTLEGE_TILGANG_HENTET = 'FASTLEGE_TILGANG_HENTET';

export const PUSH_MODIACONTEXT_FORESPURT = 'PUSH_MODIACONTEXT_FORESPURT';
export const PUSH_MODIACONTEXT_FEILET = 'PUSH_MODIACONTEXT_FEILET';
export const MODIACONTEXT_PUSHET = 'MODIACONTEXT_PUSHET';
export const PUSHER_MODIACONTEXT = 'PUSHER_MODIACONTEXT';

export const HENT_AKTIVENHET_FORESPURT = 'HENT_AKTIVENHET_FORESPURT';
export const HENTER_AKTIVENHET = 'HENTER_AKTIVENHET';
export const HENT_AKTIVENHET_FEILET = 'HENT_AKTIVENHET_FEILET';
export const AKTIVENHET_HENTET = 'AKTIVENHET_HENTET';
